type GoalDetailParams = {
  targetLift?: string;
  current1RM?: string;
  target1RM?: string;
  secondaryLift?: string;
  priorityMuscles?: string[];
  startingWeightLbs?: string;
  targetWeightLbs?: string;
  targetDate?: string;
  targetBodyFatPct?: string;
  recompFocus?: string;
  generalFocus?: string;
  planDuration?: string;
};

export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  GoalDetails: { goal: string };
  Experience: { goal: string } & GoalDetailParams;
  Constraints: {
    goal: string;
    experience: string;
    daysPerWeek: string;
    sessionLength: string;
    split: string;
  } & GoalDetailParams;
  BodyMetrics: {
    goal: string;
    experience: string;
    daysPerWeek: string;
    sessionLength: string;
    split: string;
    injuries: string[];
    equipment: string;
    weakPoints: string[];
    excludedExercises: string[];
  } & GoalDetailParams;
  MacroSetup: {
    goal: string;
    experience: string;
    daysPerWeek: string;
    sessionLength: string;
    split: string;
    injuries: string[];
    equipment: string;
    weakPoints: string[];
    excludedExercises: string[];
    age: string;
    sex: string;
    heightFt: string;
    heightIn: string;
    weightLbs: string;
    bodyFatPct: string | null;
  } & GoalDetailParams;
  PlanPreview: {
    goal: string;
    experience: string;
    daysPerWeek: string;
    sessionLength: string;
    split: string;
    injuries: string[];
    equipment: string;
    weakPoints: string[];
    excludedExercises: string[];
    age: string;
    sex: string;
    heightFt: string;
    heightIn: string;
    weightLbs: string;
    bodyFatPct: string | null;
    calories: number;
    proteinG: number;
    carbsG: number;
    fatsG: number;
  } & GoalDetailParams;
  BuildingPlan: {
    goal: string;
    experience: string;
    daysPerWeek: string;
    sessionLength: string;
    split: string;
    injuries: string[];
    equipment: string;
    weakPoints: string[];
    excludedExercises: string[];
    age: string;
    sex: string;
    heightFt: string;
    heightIn: string;
    weightLbs: string;
    bodyFatPct: string | null;
    calories: number;
    proteinG: number;
    carbsG: number;
    fatsG: number;
  } & GoalDetailParams;
  Dashboard: undefined;
  ActiveWorkout: {
    planId: string;
    weekNumber: number;
    dayNumber: number;
    workoutTitle?: string;
  };
  WorkoutComplete: {
    planId: string;
    weekNumber: number;
    dayNumber: number;
    totalSets: number;
    totalExercises: number;
    durationMinutes: number;
    fatigueRating: number;
    prsHit: number;
  };
};
