export type IngredientCategory = 'protein' | 'carb' | 'fat' | 'vegetable';

export type MealSlot = 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack';

export type DietaryStyle =
  | 'omnivore'
  | 'vegetarian'
  | 'vegan'
  | 'pescatarian'
  | 'keto'
  | 'paleo';

export type Allergen = 'Gluten' | 'Dairy' | 'Nuts' | 'Eggs' | 'Soy' | 'Shellfish';

export type Ingredient = {
  id: string;
  name: string;
  portion: string;
  calories: number;
  protein_g: number;
  carbs_g: number;
  fats_g: number;
  category: IngredientCategory;
  dietaryStyles: DietaryStyle[];
  allergens: Allergen[];
  mealSlots: MealSlot[];
};

const ALL_SLOTS: MealSlot[] = ['Breakfast', 'Lunch', 'Dinner', 'Snack'];

const ALL_DIETS: DietaryStyle[] = [
  'omnivore',
  'vegetarian',
  'vegan',
  'pescatarian',
  'keto',
  'paleo',
];

const ALL_EXCEPT_KETO: DietaryStyle[] = [
  'omnivore',
  'vegetarian',
  'vegan',
  'pescatarian',
  'paleo',
];

const OVV: DietaryStyle[] = ['omnivore', 'vegetarian', 'vegan', 'pescatarian'];

export const INGREDIENTS: Ingredient[] = [
  // PROTEINS (15)
  {
    id: 'chicken-breast',
    name: 'Chicken Breast',
    portion: '6 oz',
    calories: 280,
    protein_g: 52,
    carbs_g: 0,
    fats_g: 6,
    category: 'protein',
    dietaryStyles: ['omnivore', 'pescatarian', 'paleo'],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'ground-turkey',
    name: 'Ground Turkey',
    portion: '5 oz',
    calories: 200,
    protein_g: 30,
    carbs_g: 0,
    fats_g: 8,
    category: 'protein',
    dietaryStyles: ['omnivore', 'paleo'],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'salmon-fillet',
    name: 'Salmon Fillet',
    portion: '6 oz',
    calories: 350,
    protein_g: 40,
    carbs_g: 0,
    fats_g: 20,
    category: 'protein',
    dietaryStyles: ['omnivore', 'pescatarian', 'paleo'],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'whole-eggs-2',
    name: 'Whole Eggs (2)',
    portion: '2 eggs',
    calories: 140,
    protein_g: 12,
    carbs_g: 1,
    fats_g: 10,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'keto', 'paleo'],
    allergens: ['Eggs'],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'egg-whites-4',
    name: 'Egg Whites (4)',
    portion: '4 whites',
    calories: 70,
    protein_g: 14,
    carbs_g: 1,
    fats_g: 0,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'keto', 'paleo'],
    allergens: ['Eggs'],
    mealSlots: ['Breakfast'],
  },
  {
    id: 'greek-yogurt',
    name: 'Greek Yogurt',
    portion: '1 cup',
    calories: 130,
    protein_g: 22,
    carbs_g: 9,
    fats_g: 0,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'keto'],
    allergens: ['Dairy'],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'cottage-cheese',
    name: 'Cottage Cheese',
    portion: '1 cup',
    calories: 180,
    protein_g: 24,
    carbs_g: 8,
    fats_g: 5,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'keto'],
    allergens: ['Dairy'],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'tuna-canned',
    name: 'Tuna (canned)',
    portion: '5 oz',
    calories: 150,
    protein_g: 33,
    carbs_g: 0,
    fats_g: 1,
    category: 'protein',
    dietaryStyles: ['omnivore', 'pescatarian', 'paleo'],
    allergens: [],
    mealSlots: ['Lunch'],
  },
  {
    id: 'lean-ground-beef',
    name: 'Lean Ground Beef',
    portion: '5 oz',
    calories: 250,
    protein_g: 32,
    carbs_g: 0,
    fats_g: 13,
    category: 'protein',
    dietaryStyles: ['omnivore', 'paleo'],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'tofu-firm',
    name: 'Tofu (firm)',
    portion: '6 oz',
    calories: 120,
    protein_g: 14,
    carbs_g: 3,
    fats_g: 6,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: ['Soy'],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'tempeh',
    name: 'Tempeh',
    portion: '4 oz',
    calories: 160,
    protein_g: 15,
    carbs_g: 8,
    fats_g: 9,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: ['Soy'],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    portion: '6 oz',
    calories: 170,
    protein_g: 32,
    carbs_g: 2,
    fats_g: 2,
    category: 'protein',
    dietaryStyles: ['omnivore', 'pescatarian', 'paleo'],
    allergens: ['Shellfish'],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'whey-protein-shake',
    name: 'Whey Protein Shake',
    portion: '1 scoop+water',
    calories: 120,
    protein_g: 24,
    carbs_g: 3,
    fats_g: 2,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian'],
    allergens: ['Dairy'],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'black-beans',
    name: 'Black Beans',
    portion: '1 cup',
    calories: 220,
    protein_g: 15,
    carbs_g: 40,
    fats_g: 1,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'lentils',
    name: 'Lentils',
    portion: '1 cup',
    calories: 230,
    protein_g: 18,
    carbs_g: 40,
    fats_g: 1,
    category: 'protein',
    dietaryStyles: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },

  // CARBS (15)
  {
    id: 'white-rice',
    name: 'White Rice',
    portion: '1 cup cooked',
    calories: 200,
    protein_g: 4,
    carbs_g: 44,
    fats_g: 0,
    category: 'carb',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'brown-rice',
    name: 'Brown Rice',
    portion: '1 cup cooked',
    calories: 215,
    protein_g: 5,
    carbs_g: 45,
    fats_g: 2,
    category: 'carb',
    dietaryStyles: [...ALL_EXCEPT_KETO],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'rolled-oats',
    name: 'Rolled Oats',
    portion: '1/2 cup dry',
    calories: 150,
    protein_g: 5,
    carbs_g: 27,
    fats_g: 3,
    category: 'carb',
    dietaryStyles: ['omnivore', 'vegetarian', 'vegan', 'pescatarian'],
    allergens: ['Gluten'],
    mealSlots: ['Breakfast'],
  },
  {
    id: 'sweet-potato',
    name: 'Sweet Potato',
    portion: '1 medium',
    calories: 130,
    protein_g: 2,
    carbs_g: 30,
    fats_g: 0,
    category: 'carb',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'white-potato',
    name: 'White Potato',
    portion: '1 medium',
    calories: 160,
    protein_g: 4,
    carbs_g: 37,
    fats_g: 0,
    category: 'carb',
    dietaryStyles: [...ALL_EXCEPT_KETO],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'whole-wheat-pasta',
    name: 'Whole Wheat Pasta',
    portion: '2 oz dry',
    calories: 180,
    protein_g: 7,
    carbs_g: 37,
    fats_g: 1,
    category: 'carb',
    dietaryStyles: OVV,
    allergens: ['Gluten'],
    mealSlots: ['Dinner'],
  },
  {
    id: 'white-pasta',
    name: 'White Pasta',
    portion: '2 oz dry',
    calories: 200,
    protein_g: 7,
    carbs_g: 41,
    fats_g: 1,
    category: 'carb',
    dietaryStyles: OVV,
    allergens: ['Gluten'],
    mealSlots: ['Dinner'],
  },
  {
    id: 'sourdough-bread',
    name: 'Sourdough Bread (2 slices)',
    portion: '2 slices',
    calories: 160,
    protein_g: 6,
    carbs_g: 32,
    fats_g: 1,
    category: 'carb',
    dietaryStyles: OVV,
    allergens: ['Gluten'],
    mealSlots: ['Breakfast', 'Lunch'],
  },
  {
    id: 'rice-cakes-3',
    name: 'Rice Cakes (3)',
    portion: '3 cakes',
    calories: 105,
    protein_g: 2,
    carbs_g: 23,
    fats_g: 0,
    category: 'carb',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'banana',
    name: 'Banana',
    portion: '1 medium',
    calories: 105,
    protein_g: 1,
    carbs_g: 27,
    fats_g: 0,
    category: 'carb',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    portion: '1 cup',
    calories: 85,
    protein_g: 1,
    carbs_g: 21,
    fats_g: 0,
    category: 'carb',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'quinoa',
    name: 'Quinoa',
    portion: '1 cup cooked',
    calories: 220,
    protein_g: 8,
    carbs_g: 39,
    fats_g: 4,
    category: 'carb',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'corn-tortillas-2',
    name: 'Corn Tortillas (2)',
    portion: '2 tortillas',
    calories: 120,
    protein_g: 3,
    carbs_g: 24,
    fats_g: 1,
    category: 'carb',
    dietaryStyles: [...ALL_EXCEPT_KETO],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'bagel-1',
    name: 'Bagel (1 whole)',
    portion: '1 bagel',
    calories: 270,
    protein_g: 10,
    carbs_g: 53,
    fats_g: 1,
    category: 'carb',
    dietaryStyles: OVV,
    allergens: ['Gluten'],
    mealSlots: ['Breakfast'],
  },
  {
    id: 'honey',
    name: 'Honey',
    portion: '1 tbsp',
    calories: 60,
    protein_g: 0,
    carbs_g: 17,
    fats_g: 0,
    category: 'carb',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'paleo'],
    allergens: [],
    mealSlots: ['Breakfast', 'Snack'],
  },

  // FATS (10)
  {
    id: 'avocado',
    name: 'Avocado',
    portion: '1/2 medium',
    calories: 120,
    protein_g: 1,
    carbs_g: 6,
    fats_g: 11,
    category: 'fat',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner', 'Snack'],
  },
  {
    id: 'olive-oil',
    name: 'Olive Oil',
    portion: '1 tbsp',
    calories: 120,
    protein_g: 0,
    carbs_g: 0,
    fats_g: 14,
    category: 'fat',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'peanut-butter',
    name: 'Peanut Butter',
    portion: '2 tbsp',
    calories: 190,
    protein_g: 8,
    carbs_g: 6,
    fats_g: 16,
    category: 'fat',
    dietaryStyles: [...ALL_DIETS],
    allergens: ['Nuts'],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'almond-butter',
    name: 'Almond Butter',
    portion: '2 tbsp',
    calories: 200,
    protein_g: 7,
    carbs_g: 6,
    fats_g: 18,
    category: 'fat',
    dietaryStyles: [...ALL_DIETS],
    allergens: ['Nuts'],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'almonds',
    name: 'Almonds',
    portion: '1oz (23 nuts)',
    calories: 160,
    protein_g: 6,
    carbs_g: 6,
    fats_g: 14,
    category: 'fat',
    dietaryStyles: [...ALL_DIETS],
    allergens: ['Nuts'],
    mealSlots: ['Snack'],
  },
  {
    id: 'walnuts',
    name: 'Walnuts',
    portion: '1 oz',
    calories: 185,
    protein_g: 4,
    carbs_g: 4,
    fats_g: 18,
    category: 'fat',
    dietaryStyles: [...ALL_DIETS],
    allergens: ['Nuts'],
    mealSlots: ['Snack'],
  },
  {
    id: 'cheddar-cheese',
    name: 'Cheddar Cheese',
    portion: '1 oz',
    calories: 115,
    protein_g: 7,
    carbs_g: 0,
    fats_g: 9,
    category: 'fat',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'keto'],
    allergens: ['Dairy'],
    mealSlots: ['Breakfast', 'Lunch', 'Snack'],
  },
  {
    id: 'coconut-oil',
    name: 'Coconut Oil',
    portion: '1 tbsp',
    calories: 120,
    protein_g: 0,
    carbs_g: 0,
    fats_g: 14,
    category: 'fat',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Breakfast', 'Lunch', 'Dinner'],
  },
  {
    id: 'full-fat-greek-yogurt',
    name: 'Full Fat Greek Yogurt',
    portion: '1/2 cup',
    calories: 110,
    protein_g: 9,
    carbs_g: 5,
    fats_g: 6,
    category: 'fat',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'keto'],
    allergens: ['Dairy'],
    mealSlots: ['Breakfast', 'Snack'],
  },
  {
    id: 'egg-yolks-2',
    name: 'Egg Yolks (2)',
    portion: '2 yolks',
    calories: 110,
    protein_g: 5,
    carbs_g: 1,
    fats_g: 9,
    category: 'fat',
    dietaryStyles: ['omnivore', 'vegetarian', 'pescatarian', 'keto', 'paleo'],
    allergens: ['Eggs'],
    mealSlots: ['Breakfast'],
  },

  // VEGETABLES (10)
  {
    id: 'broccoli',
    name: 'Broccoli',
    portion: '1 cup steamed',
    calories: 55,
    protein_g: 4,
    carbs_g: 11,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: [...ALL_SLOTS],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    portion: '2 cups raw',
    calories: 15,
    protein_g: 2,
    carbs_g: 2,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: [...ALL_SLOTS],
  },
  {
    id: 'mixed-salad-greens',
    name: 'Mixed Salad Greens',
    portion: '2 cups',
    calories: 15,
    protein_g: 1,
    carbs_g: 2,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'cherry-tomatoes',
    name: 'Cherry Tomatoes',
    portion: '1 cup',
    calories: 30,
    protein_g: 1,
    carbs_g: 6,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: [...ALL_SLOTS],
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    portion: '1 cup sliced',
    calories: 15,
    protein_g: 1,
    carbs_g: 3,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: [...ALL_SLOTS],
  },
  {
    id: 'bell-pepper',
    name: 'Bell Pepper',
    portion: '1 medium',
    calories: 30,
    protein_g: 1,
    carbs_g: 7,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: [...ALL_SLOTS],
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    portion: '1 cup',
    calories: 20,
    protein_g: 1,
    carbs_g: 4,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    portion: '1 cup',
    calories: 27,
    protein_g: 3,
    carbs_g: 5,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'green-beans',
    name: 'Green Beans',
    portion: '1 cup',
    calories: 35,
    protein_g: 2,
    carbs_g: 8,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: ['Lunch', 'Dinner'],
  },
  {
    id: 'mushrooms',
    name: 'Mushrooms',
    portion: '1 cup sliced',
    calories: 15,
    protein_g: 2,
    carbs_g: 2,
    fats_g: 0,
    category: 'vegetable',
    dietaryStyles: [...ALL_DIETS],
    allergens: [],
    mealSlots: [...ALL_SLOTS],
  },
];

export function getFilteredIngredients(
  category: IngredientCategory,
  slot: MealSlot,
  dietaryStyle: DietaryStyle,
  allergies: Allergen[],
): Ingredient[] {
  return INGREDIENTS.filter(
    (ing) =>
      ing.category === category &&
      ing.mealSlots.includes(slot) &&
      ing.dietaryStyles.includes(dietaryStyle) &&
      !ing.allergens.some((a) => allergies.includes(a)),
  );
}
