import { supabase } from './supabase';
import { setRecordsSupabaseClient } from './recordsCore';

setRecordsSupabaseClient(supabase);

export {
  afterFreeSessionSaved,
  afterWorkoutLogSaved,
  backfillRecordsForUser,
  confirmFlaggedSet,
  confirmSetInParsedSets,
  countFlaggedSetsInJson,
  computeExerciseRecordFromQualifyingSets,
  estimateE1RM,
  exerciseKeysFromSets,
  flattenSetsFromSessions,
  flattenWorkoutLogSets,
  getExerciseRecords,
  getPrCountForWorkoutLogIds,
  getSessionOutcome,
  isExerciseKeyExcludedFromRecords,
  isTimedRawSet,
  parseSetsJson,
  plausibilityStatusForLoad,
  plausibilityStatusForRawSet,
  recomputeExerciseRecords,
  recomputeExerciseRecordsForKeys,
  resolveExerciseKey,
  setRecordsSupabaseClient,
  shouldExcludeSetFromRecords,
  slugExerciseName,
  updateSessionLoggedSet,
  updateSetInParsedSets,
  type ConfirmFlaggedSetParams,
  type EstimateE1RMInput,
  type ExerciseRecordComputed,
  type ExerciseRecordDisplay,
  type QualifyingLoggedSetRow,
  type RawLoggedSetInput,
  type ResolvedExerciseKey,
  type SessionOutcome,
  type SessionSource,
  type UpdateSessionLoggedSetParams,
} from './recordsCore';
